export const DICTIONARY = [
  { word: "rizz", definition: "Style, charm, or attractiveness, and the ability to attract people. It can also refer to the ability to attract a romantic or sexual partner. Example: She has more rizz than anyone I've ever met." },
  { word: "slay", definition: "To do something spectacularly well or succeed in an impressive way. Example: She absolutely slayed her performance at the concert." },
  { word: "sus", definition: "Suspicious or suspect. Example: That guy hanging around the car looks kinda sus." },
  { word: "vibe", definition: "A person's emotional state or the atmosphere of a place. Example: The café had such a chill vibe, I could stay there all day." },
  { word: "AFK", definition: "Away From Keyboard. Used to indicate that someone is temporarily unavailable or not at their computer. Example: BRB, going AFK for dinner." },
  { word: "AMA", definition: "Ask Me Anything. Commonly used in online forums for a Q&A session. Example: I'm a software engineer, AMA!" },
  { word: "ASAP", definition: "As Soon As Possible. A request for something to be done quickly. Example: Please send me the report ASAP." },
  { word: "aesthetic", definition: "A particular style or vibe that someone finds visually pleasing. Example: Her Instagram feed has such a dreamy aesthetic." },
  { word: "bussin", definition: "Really good, amazing. Especially used for food." },
  { word: "no cap", definition: "No lie, for real. Used to emphasize truthfulness." },
  { word: "fr fr", definition: "For real, for real (emphasizing truth)" },
  { word: "tea", definition: "Gossip or drama. Example: Spill the tea about what happened!" },
  { word: "drip", definition: "Stylish or fashionable attire. Example: Your outfit has serious drip!" },
  { word: "based", definition: "To be yourself and not care about how others view you. Now used to indicate an opinion or something someone agrees with." },
  { word: "cap", definition: "A lie or to lie about something." },
  { word: "caught in 4k", definition: "Refers to someone being caught doing something wrong or incriminating on camera or with evidence to prove it." },
  { word: "cook", definition: "\"Someone cooked here\" & \"Let him cook\" = give space for potentially messy (but entertaining) actions." },
  { word: "clapback", definition: "Swift and witty response to an insult or critique." },
  { word: "CEO", definition: "Used to indicate someone who is the best at a particular thing, e.g., \"CEO of memes\"." },
  { word: "canceled", definition: "To stop supporting someone. Usually due to their problematic behavior." },
  { word: "catch feelings", definition: "To develop romantic feelings for someone." },
  { word: "clout", definition: "Influence or fame. Especially on social media." },
  { word: "cuffed", definition: "Being in a committed relationship." },
  { word: "curve", definition: "To reject someone's romantic advances." },
  { word: "capping", definition: "Lying." },
  { word: "cheugy", definition: "Outdated or trying too hard. Especially in terms of fashion or lifestyle." },
  { word: "chill", definition: "Relaxed or easygoing." },
  { word: "clout chaser", definition: "Someone who does things for fame or influence." },
  { word: "chillax", definition: "To calm down and relax." },
  { word: "clutch", definition: "Describing a crucial or game-changing moment." },
  { word: "cray", definition: "Crazy." },
  { word: "DM", definition: "Direct Message - A private message sent on social media platforms." },
  { word: "drip", definition: "Stylish or fashionable attire." },
  { word: "dab", definition: "A dance move used as a gesture of triumph." },
  { word: "dub", definition: "Win or victory." },
  { word: "deadass", definition: "Seriously or genuinely." },
  { word: "dying", definition: "Laughing really hard." },
  { word: "deets", definition: "Details." },
  { word: "dip", definition: "To leave abruptly." },
  { word: "doxxing", definition: "Publishing private information about someone without their consent." },
  { word: "dank", definition: "Very cool or awesome; often used to describe memes." },
  { word: "dope", definition: "Cool or awesome." },
  { word: "drop", definition: "To release something, often used for music or fashion." },
  { word: "dead", definition: "Extremely funny or entertaining." },
  { word: "defo", definition: "Definitely." },
  { word: "dolla dolla bills", definition: "Money; from a Wu-Tang Clan lyric." },
  { word: "do her", definition: "Performing sexual intimacy with her." },
  { word: "do him", definition: "Performing sexual intimacy with him." },
  { word: "doable", definition: "Attractive or sexually appealing." },
  { word: "ded", definition: "Used to describe something humorous to such an extent as to 'kill you.'" },
  { word: "DTF", definition: "Down to Fuck; someone who has agreed on having sex." },
  { word: "extra", definition: "Over-the-top; excessive dramatic behavior." },
  { word: "eboy/egirl", definition: "A young person with a specific online aesthetic, often associated with TikTok." },
  { word: "edgy", definition: "Trying to be cool by being controversial or provocative." },
  { word: "emo", definition: "A style associated with emotional expression and a distinct music genre." },
  { word: "epic", definition: "Extremely impressive or extraordinary." },
  { word: "exposed", definition: "To reveal someone's secrets or embarrassing information." },
  { word: "ethereal", definition: "Extremely delicate or refined; often used to describe beauty." },
  { word: "effing", definition: "A nicer way of saying 'f**king'." },
  { word: "FFS", definition: "For F**k's Sake; an expression of frustration or exasperation." },
  { word: "FOMO", definition: "Fear Of Missing Out; anxiety about missing an exciting event." },
  { word: "FTW", definition: "For The Win; used to express enthusiasm for something." },
  { word: "FWIW", definition: "For What It's Worth; used to introduce a statement that may or may not be considered valuable." },
  { word: "fam", definition: "Close friends or family." },
  { word: "feels", definition: "Emotions or feelings." },
  { word: "finesse", definition: "To cleverly handle a situation or manipulate someone." },
  { word: "finsta", definition: "Fake Instagram; a secondary account for more private content." },
  { word: "fit", definition: "Outfit." },
  { word: "finna", definition: "Going to or intending to (derived from 'fixing to')." },
  { word: "fleek", definition: "On point or very good." },
  { word: "flex", definition: "To show off or boast about something." },
  { word: "facts", definition: "Agreeing with something that is undeniably true." },
  { word: "fake deep", definition: "Pretending to be profound or insightful." },
  { word: "fire", definition: "Really good or impressive." },
  { word: "frontin'", definition: "Pretending or putting up a false appearance." },
  { word: "fapping", definition: "Masturbation." },
  { word: "fleabagging", definition: "Dating and breaking up, then making up with the wrong person over and over." },
  { word: "ghosting", definition: "Suddenly cutting off all communication with someone without explanation." },
  { word: "glow up", definition: "A noticeable improvement in appearance, style, or overall life." },
  { word: "GOAT", definition: "Greatest Of All Time; used to praise someone who is considered the best." },
  { word: "goated", definition: "Outstanding or excellent." },
  { word: "goals", definition: "Aspirational; used to describe something or someone one wants to emulate." },
  { word: "gassed", definition: "Feeling very excited or pumped up." },
  { word: "grind", definition: "Hard work or hustle." },
  { word: "gucci", definition: "Cool or good, taken from the luxury brand." },
  { word: "gloup", definition: "A major improvement in someone's appearance, style, or overall life." },
  { word: "hits different", definition: "When something feels or affects you in a unique way compared to other similar things." },
  { word: "highkey", definition: "Openly or obviously; the opposite of lowkey." },
  { word: "hundo P", definition: "100 percent; completely sure." },
  { word: "hangry", definition: "Irritable due to hunger." },
  { word: "hype", definition: "Excitement or enthusiastic promotion." },
  { word: "hot take", definition: "An unpopular or controversial opinion." },
  { word: "hyped", definition: "Extremely excited." },
  { word: "hella", definition: "Hell of; a lot or very." },
  { word: "hood", definition: "Short for neighborhood, often used to describe a rough area." },
  { word: "hypebeast", definition: "Someone who follows the latest trends and only buys trendy, high-end brands." },
  { word: "hundo", definition: "Hundred." },
  { word: "hold up", definition: "Wait a moment or pause." },
  { word: "heaux", definition: "A variant of the word 'hoe,' used in reference to a promiscuous woman." },
  { word: "IDK", definition: "I Don't Know." },
  { word: "IKR", definition: "I Know, Right? Used to agree with something that was just said." },
  { word: "IMHO", definition: "In My Humble Opinion." },
  { word: "incel", definition: "Involuntary Celibate; someone who struggles with romantic or sexual relationships." },
  { word: "IYKYK", definition: "If You Know, You Know." },
  { word: "irr", definition: "Irritated." },
  { word: "IRL", definition: "In Real Life." },
  { word: "It's giving", definition: "Used to express how something or someone feels or looks in a way that aligns with a particular vibe." },
  { word: "juice", definition: "Cool or impressive; also slang for influence or power." },
  { word: "janky", definition: "Poor quality or unreliable." },
  { word: "jelly", definition: "Jealous." },
  { word: "k", definition: "Okay." },
  { word: "karen", definition: "A derogatory term for an entitled, demanding woman." },
  { word: "kiki", definition: "A fun social gathering or event, often for gossip or drama." },
  { word: "king", definition: "A term of respect, often used for a man." },
  { word: "kickback", definition: "A laid-back social gathering or party." },
  { word: "knope", definition: "A term used to describe being unsure or skeptical." },
  { word: "lit", definition: "Exciting, cool, or fun." },
  { word: "lowkey", definition: "Not obvious or subtle, often used to express something secretly." },
  { word: "lmao", definition: "Laughing My Ass Off." },
  { word: "lms", definition: "Like My Status." },
  { word: "loud", definition: "Bold or attention-grabbing." },
  { word: "litty", definition: "Very lit." },
  { word: "lunchable", definition: "Something small, often refers to a convenience food." },
  { word: "looped", definition: "To be intoxicated, typically from alcohol or drugs." },
  { word: "loss", definition: "To fail or lose." },
  { word: "look", definition: "Used when introducing an opinion or perspective." },
  { word: "lewk", definition: "A personal style or outfit." },
  { word: "lmfao", definition: "Laughing My Freaking Ass Off." },
  { word: "man cave", definition: "A space or room in a house for men to relax in." },
  { word: "my bad", definition: "An apology for making a mistake." },
  { word: "mad", definition: "Very or extremely." },
  { word: "MFW", definition: "My Face When. Used to describe one's reaction to something." },
  { word: "MVP", definition: "Most valuable player." },
  { word: "MO", definition: "Modus Operandi; used to describe someone's typical behavior." },
  { word: "monkey", definition: "An insult referring to clumsiness or stupidity." },
  { word: "mood", definition: "A feeling or emotion someone experiences." },
  { word: "muse", definition: "A person who inspires creativity or artistic expression." },
  { word: "mask", definition: "To hide or disguise one's true feelings." },
  { word: "meme", definition: "A humorous or viral image, video, or text." },
  { word: "millennial", definition: "A person born between 1981-1996, associated with technological advancements and shifting social values." },
  { word: "mega", definition: "Extremely good or impressive." },
  { word: "morning", definition: "Shortened as a greeting." },
  { word: "moments", definition: "Memories or occurrences." },
  { word: "man-bun", definition: "A hairstyle where long hair is tied up in a bun." },
  { word: "muva", definition: "A variant of 'mother,' used for a powerful or influential woman." },
  { word: "munch", definition: "Sexual appetite." },
  { word: "mac", definition: "A friend or pal." },
  { word: "mine", definition: "A personal possession or term of endearment." },
  { word: "mood", definition: "State or disposition." },
  { word: "man-child", definition: "An adult man who displays immaturity." },
  { word: "morals", definition: "A code of conduct or values." },
  { word: "muh", definition: "Commonly used in sentences indicating self-explanation or self-realization." },
  { word: "meme-tastic", definition: "Indicating something is funny, or great as a meme." },
  { word: "mash", definition: "To collide or grind." },
  { word: "nana", definition: "Grandmother, often used in an affectionate way." },
  { word: "napping", definition: "Taking a brief rest or sleep." },
  { word: "neurodivergent", definition: "Describes someone whose brain processes differently from the typical or standard." },
  { word: "noob", definition: "A beginner or novice, often used in online gaming." },
  { word: "no cap", definition: "No lie or truth." },
  { word: "naked", definition: "Bare, without clothes." },
  { word: "nft", definition: "Non-Fungible Token; a unique digital asset." },
  { word: "newb", definition: "Another term for a beginner or novice." },
  { word: "nitpick", definition: "To focus on small, insignificant issues." },
  { word: "nightcap", definition: "A final drink before bed." },
  { word: "on fleek", definition: "On point, flawless." },
  { word: "on god", definition: "A phrase used to emphasize the truth or sincerity of a statement." },
  { word: "OTW", definition: "On The Way." },
  { word: "OG", definition: "Original Gangster; someone who is authentic, respected, or experienced." },
  { word: "OTP", definition: "One True Pairing; a couple, real or fictional, that is seen as perfect." },
  { word: "overload", definition: "To overwhelm or exceed limits." },
  { word: "overthink", definition: "To think too much about something, usually leading to unnecessary worry." },
  { word: "plz", definition: "Please." },
  { word: "pinned", definition: "A message or post that has been marked as important and kept at the top of a feed." },
  { word: "popping", definition: "Very lively, exciting, or fashionable." },
  { word: "PM", definition: "Private Message." },
  { word: "POV", definition: "Point Of View; often used to describe a perspective or a situation from someone's viewpoint." },
  { word: "pressing", definition: "Urgent or important." },
  { word: "petty", definition: "Being overly concerned with trivial matters, often with the intent to annoy." },
  { word: "pet", definition: "To show affection to someone or something." },
  { word: "peep", definition: "To look at or observe something." },
  { word: "popping off", definition: "To do something with great energy or excitement." },
  { word: "plot twist", definition: "A surprising change in the expected course of events." },
  { word: "pissed", definition: "Angry." },
  { word: "pause", definition: "To stop something temporarily or reconsider before continuing." },
  { word: "queer", definition: "A term used to describe someone who does not fit into the traditional categories of sexual orientation or gender identity." },
  { word: "quick flex", definition: "To quickly show off or brag about something." },
  { word: "queen", definition: "A term used to describe a powerful or respected woman." },
  { word: "quietly", definition: "In a calm or subdued manner." },
  { word: "relationship goals", definition: "A term used to describe what one aspires to have in a relationship." },
  { word: "roast", definition: "To humorously criticize or mock someone." },
  { word: "ratchet", definition: "Someone or something that is ghetto or trashy." },
  { word: "reality check", definition: "A realization or reminder of the true nature of a situation." },
  { word: "real talk", definition: "A conversation that is honest or direct." },
  { word: "reel", definition: "A social media post, particularly on Instagram, similar to TikTok videos." },
  { word: "rev", definition: "Rev up, or to increase speed or intensity." },
  { word: "receipts", definition: "Evidence or proof, usually of something that someone has said or done." },
  { word: "roll the dice", definition: "To take a risk." },
  { word: "shook", definition: "Shocked or surprised." },
  { word: "shade", definition: "Subtle or indirect criticism." },
  { word: "savage", definition: "Someone or something that is bold, fierce, or ruthless." },
  { word: "simp", definition: "Someone who is overly attentive or submissive to someone they are attracted to, often in a way considered excessive." },
  { word: "slay", definition: "To perform exceptionally well or to look outstanding." },
  { word: "slaps", definition: "Something that is very good or impressive, usually in reference to music." },
  { word: "sliding into DMs", definition: "Sending someone a private message, often with a romantic or flirtatious intent." },
  { word: "squad", definition: "A group of close friends or associates." },
  { word: "savage", definition: "Bold, daring, and unapologetically confident." },
  { word: "stan", definition: "To be a huge fan of someone or something." },
  { word: "spill the tea", definition: "To share gossip or news." },
  { word: "sus", definition: "Suspicious; used to describe something that seems off or shady." },
  { word: "thirsty", definition: "Desperate for attention, especially romantic or sexual." },
  { word: "thicc", definition: "A term used to describe a person with a curvy or fuller body." },
  { word: "tbh", definition: "To Be Honest." },
  { word: "tldr", definition: "Too Long; Didn't Read. Used to summarize a long message or text." },
  { word: "tea", definition: "Gossip or the latest news." },
  { word: "throw shade", definition: "To subtly insult or criticize someone." },
  { word: "top tier", definition: "The best or highest quality." },
  { word: "toxic", definition: "Unhealthy or harmful, especially in relationships." },
  { word: "vibe", definition: "The overall feeling or atmosphere of a place or situation." },
  { word: "vibing", definition: "Feeling the mood or enjoying the atmosphere." },
  { word: "vsco girl", definition: "A stereotype of a young woman who dresses casually, loves taking aesthetic photos, and uses products like Hydro Flasks." },
  { word: "woke", definition: "Awareness of social injustices and inequalities, particularly related to race or gender." },
  { word: "YOLO", definition: "You Only Live Once. Used to express the idea that life is short and one should take risks or seize opportunities." },
  { word: "yasss", definition: "An enthusiastic affirmation or celebration." },
  { word: "yikes", definition: "Used to express discomfort or embarrassment." },
  { word: "zaddy", definition: "A term for an attractive man, often used to describe someone with confidence and style." }
];

export const SHORTCUTS = {
  "General": {
    "BRB": "Be Right Back",
    "GTG/G2G": "Got To Go",
    "TTYL": "Talk To You Later",
    "LOL": "Laugh Out Loud",
    "ROFL": "Rolling On the Floor Laughing",
    "LMAO": "Laughing My Ass Off",
    "SMH": "Shaking My Head",
    "IDC": "I Don't Care",
    "IDK": "I Don't Know",
    "TBH": "To Be Honest",
    "IMO": "In My Opinion",
    "IMHO": "In My Humble Opinion",
    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "OMG": "Oh My God",
    "OMW": "On My Way",
    "TTFN": "Ta-Ta For Now",
    "CYA": "See You",
    "NVM": "Never Mind",
    "YOLO": "You Only Live Once",
    "AF": "As F*** (used for emphasis)",
    "BAU": "Business As Usual",
    "IK": "I Know",
    "KK": "Okay, Cool",
    "KYS": "Keep Yourself Safe",
    "L8R": "Later",
    "OFC": "Of Course",
    "SRSLY": "Seriously",
    "SUX": "Sucks",
    "WBU": "What About You",
    "WYD": "What You Doing",
    "IDTS": "I Don't Think So",
    "JK": "Just Kidding",
    "SMDH": "Shaking My Damn Head",
    "WFH": "Work From Home",
    "TL;DR": "Too Long; Didn't Read",
    "OOT": "Out Of Town",
    "NRN": "No Reply Necessary",
    "PLS": "Please",
    "TBA": "To Be Announced",
    "EOD": "End Of Day",
    "KPI": "Key Performance Indicator",
    "ETA": "Estimated Time of Arrival",
    "WCW": "Woman Crush Wednesday",
    "MCM": "Man Crush Monday",
    "TBF": "To Be Fair",
    "FAF": "Funny As F***",
    "ILYSM": "I Love You So Much",
    "TYT": "Take Your Time",
    "BAE": "Before Anyone Else",
    "BRUH": "Brother (or used for disbelief)",
    "SZN": "Season",
    "WP": "Well Played",
    "EZ": "Easy",
    "NERF": "Reduce power",
    "BUFF": "Enhance power",
    "RL": "Real Life",
    "PvP": "Player vs. Player",
    "BR": "Battle Royale",
    "NSP": "No Scope",
    "OTW": "On The Way",
    "FML": "F*** My Life",
    "ILY2": "I Love You Too",
    "GAH": "Frustration sound",
    "PPL": "People",
    "SMOL": "Small and cute",
    "FR": "For Real",
    "2DAY": "Today",
    "2MOR": "Tomorrow",
    "YEST": "Yesterday",
    "24/7": "24 Hours, 7 Days A Week",
    "GOAT": "Greatest Of All Time",
    "TOTP": "Top Of The Page",
    "FYP": "For You Page",
    "GR8": "Great",
    "SUP": "What's Up?",
    "XOXO": "Hugs and Kisses",
    "FTW": "For The Win",
    "B4": "Before",
    "BTW": "By The Way",
    "TYVM": "Thank You Very Much"
  }
};
